# Generated by Django 4.0.4 on 2022-04-15 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('ipaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(choices=[('web_server', 'web_server'), ('db_server', 'db_server'), ('firewall', 'firewall'), ('ad_server', 'ad_server'), ('pc', 'pc'), ('oa', 'oa'), ('cms', 'cms'), ('other', 'other')], default='other', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'viper的主机表',
                'verbose_name_plural': 'viper的主机表',
                'db_table': 'viper_host',
            },
        ),
    ]
