# Generated by Django 4.0.4 on 2022-04-15 06:04

import apps.demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('update_time', models.IntegerField(default=0)),
                ('port', models.IntegerField(default=0)),
                ('banner', apps.demo.models.DiyDictField(default={})),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
